apiVersion: apps/v1
kind: Deployment
metadata:
  name: uiuiuiew
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uiuiuiew
  template:
    metadata:
      labels:
        app: uiuiuiew
    spec:
      containers:
      - image: okteto.dev/uiuiuiew:latest
        name: uiuiuiew
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "f710e65b-1a0b-4bf2-8eee-7098329b9875"
        - name: Vless_Path
          value: "/s233"
        - name: Vmess_UUID
          value: "f710e65b-1a0b-4bf2-8eee-7098329b9875"
        - name: Vmess_Path
          value: "/s244"
        - name: Share_Path
          value: "/share233"
